[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/substack-feed"
  to = "/.netlify/functions/substack-feed"
  status = 200
  force = true

[[redirects]]
  from = "/practice-library-feed"
  to = "/.netlify/functions/practice-library-feed"
  status = 200
  force = true
